### ISSUE TITLE
Demo maps not appearing

### ISSUE THREAD

**Issue by jerryhall** [ismyrnow/leaflet-groupedlayercontrol#40]
Hey there. Great work here. 
I was checking your examples and the code is in the source view but, the demo maps aren't appearing.
Thanks!

**Comment by ismyrnow** [comment]
It might have been using MapQuest tiles, which were deprecated. It seems to be working now.

Note that you'll need to click the links in the readme. The example source code will just show source code, of course, and not the maps.

**Comment by jerryhall** [comment]
I don't see a map when clicking on either link using Chrome 56.02. I do see the demos in Firefox 47.01. 
The fact I'm doing something with GIS suggests I have an idea how hyperlinks work :). I am clicking the Demo and Advanced links in your readme.

**Comment by ismyrnow** [comment]
They seem okay in Chrome 54, and I don't have Chrome Beta installed on my machine to test Chrome 56. Can you send a screenshot of what shows in the [Chrome debug console](http://stackoverflow.com/a/66434) when on the demo page?

**Comment by jerryhall** [comment]
Sure Ishmael

I just noticed the warning in the upper right of the url field which takes
me to here: https://support.google.com/chrome/answer/1342714. When I
clicked the 'load the scripts' the map appears fine and the third image
shows what I see in the console.

I hadn't noticed that, wondering if it's a new Chrome 'feature'?

Thanks a million for your work. I'll send you some links to my project when
I'm closer to finished. Actually here's a peek. I'm wishing I could style
the layers selection and legend area more but, this is how I'm going to
deliver it Friday. Plenty of time to fix it up.

Jerry



*Jerry Hall *
CivicArchive, Inc <http://CivicArchive.com>

Jerry@CivicArchive.com
858-344-1104 cell

LinkedIn <http://Linkedin.com/in/enjoypb>

**Comment by ismyrnow** [comment]
Either you're viewing the demo pages via https (check your location bar), or newer versions of Chrome are blocking external script loading via http.

The solution is to use https for script loading. I'll reopen this and provide the CDN urls for someone to use. If someone opens a PR to fix the example links in the readme as well as the urls in the example html, I'll merge it in.

https://unpkg.com/leaflet@0.7.3/dist/leaflet.js
https://unpkg.com/leaflet@0.7.3/dist/leaflet.css

**Comment by ismyrnow** [comment]
Should be fixed with #42.
