### ISSUE TITLE
make the repo name and package name consistent

### ISSUE THREAD

**Issue by sdemurjian** [ismyrnow/leaflet-groupedlayercontrol#44]
package name is 'leaflet-groupedlayercontrol' and repo name is 'Leaflet.groupedlayercontrol'

it's somewhat misleading and cost me about 30 seconds of time

**Comment by ismyrnow** [comment]
The dot in the name comes from the Leaflet plugin convention, and the dasherized name was a requirement of the npm repo. I think the latter is more important and consistent in the javascript ecosystem, so I can rename the github repo accordingly.

**Comment by ismyrnow** [comment]
Resolved in e628cee.

I haven't published a new version of the package, as github seems to be redirecting from the old address to the new one.

**Comment by sdemurjian** [comment]
Thanks!

**Comment by sdemurjian** [comment]
@ismyrnow is there value in renaming the files to follow the '-' scheme as well? it would technically be a breaking change

**Comment by ismyrnow** [comment]
I'd rather leave it the way it is, since once you've found the package, file names don't matter as much. If it wasn't a breaking change, I'd probably just do it and publish a new patch version.
