### ISSUE TITLE
unecessary checkbox

### ISSUE THREAD

**Issue by astomas** [ismyrnow/leaflet-groupedlayercontrol#45]
Hi, when adding radio button option for one  group, a checkbox is also added to the title of the checkbox group (see your advanced usage example). Can we delete/hide it?
Thx

**Comment by ismyrnow** [comment]
Yes, you can set `groupCheckboxes: false` in the options. See the example [here in the readme](https://github.com/ismyrnow/leaflet-groupedlayercontrol#advanced-usage) for how to change that setting. It should remove the checkbox next to the layer group label, but keep the checkboxes for the individual layers.
