### ISSUE TITLE
Merge with sidebar v2

### ISSUE THREAD

**Issue by mpbotti** [ismyrnow/leaflet-groupedlayercontrol#58]
Hi Ishmael! I´ve manage to move your nice menu inside a pane in Tobias Bieniek's sidebar.v2... Both plugins works together like a charm! Two thumbs up for both of you for making so terrific pice of software... 
Now I want to modify the style of your layer control so both apps can give a better user experience, but I have no clue where to start. I would like to disable the layers container box as I'm showing in next image. 
I think the solution is probably inside the CSS file, but as I said, I need a hint to accomplish this. Could you give me a hand with this? Thankyou in advance, M.

PS: This is not an issue "per se", and I think it could be manage as an enhancement, but have no idea how to qualify it like that... sorry to put it inside of "Issues"...

![captura](https://user-images.githubusercontent.com/29799871/32995561-00e8bc8a-cd55-11e7-8028-50c1926707f4.jpg)

**Comment by mpbotti** [comment]
I have figured it out by myself... thanks anyway!

**Comment by ismyrnow** [comment]
Glad you were able to work it out! I assume you found the CSS file, and were able to override the styles in there.

Yeah, Github doesn't have a great place for question type stuff like this.
